server:
  port: 8080

#?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: skill2403BOX@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

indexing-settings:
  siteConfigs:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
